const genre_list = [
    'Hip-hop',
    'R&B',
    'Indie',
    'Spatial Audio',
    'Summertime Sounds',
    'Apple Music Radio',
    'Country',
    'Feel Good',
    'Pop',
    'Latin',
    'Fitness',
    'Chill',
    'Alternative',
    'Dance',
    'Party',
    'DJ Mixes',
    'Charts',
    'Essentials',
    'Hits',
    'Electronic',
    'Music Videos',
    'Kids',
    'Family',
    'Up Next',
    'Behind the Songs',
    'Christian',
    'Urbano Latino',
    'Música Mexicana',
    'Decades',
    'Rock',
    'Classic Rock',
    'Hard Rock',
    'Metal',
    'Acoustic',
    'Classical',
    'Jazz',
    'Romance',
    'Reggae',
    'Film, TV, & Stage',
    'Focus',
    'Motivation',
    'Pop Latino',
    'K-Pop',
    'C-Pop',
    'Soul/Funk',
    'Gospel',
    'Oldies',
    'Americana',
    'Blues',
    'Wellness',
    'Worldwide',
    'African',
    'sleep'
];

export default genre_list;
